// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close(arg1) {
  return window['go']['app']['App']['Close'](arg1);
}

export function CountLines(arg1, arg2) {
  return window['go']['app']['App']['CountLines'](arg1, arg2);
}

export function Filters(arg1) {
  return window['go']['app']['App']['Filters'](arg1);
}

export function Import(arg1) {
  return window['go']['app']['App']['Import'](arg1);
}

export function LoadSettings(arg1) {
  return window['go']['app']['App']['LoadSettings'](arg1);
}

export function LuaOutput(arg1) {
  return window['go']['app']['App']['LuaOutput'](arg1);
}

export function Open(arg1) {
  return window['go']['app']['App']['Open'](arg1);
}

export function OpenWorkspaceDirectory(arg1) {
  return window['go']['app']['App']['OpenWorkspaceDirectory'](arg1);
}

export function PreviewTemplate(arg1) {
  return window['go']['app']['App']['PreviewTemplate'](arg1);
}

export function Query(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Query'](arg1, arg2, arg3, arg4);
}

export function Reload(arg1) {
  return window['go']['app']['App']['Reload'](arg1);
}

export function RunScript(arg1, arg2) {
  return window['go']['app']['App']['RunScript'](arg1, arg2);
}

export function SaveSettings(arg1, arg2) {
  return window['go']['app']['App']['SaveSettings'](arg1, arg2);
}

export function SelectLogFileDialog() {
  return window['go']['app']['App']['SelectLogFileDialog']();
}

export function SelectWorkspaceDirectoryDialog() {
  return window['go']['app']['App']['SelectWorkspaceDirectoryDialog']();
}

export function Shutdown() {
  return window['go']['app']['App']['Shutdown']();
}

export function Start(arg1) {
  return window['go']['app']['App']['Start'](arg1);
}

export function Workspaces() {
  return window['go']['app']['App']['Workspaces']();
}
