// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBookmark(arg1, arg2, arg3) {
  return window['go']['app']['Bookmarks']['AddBookmark'](arg1, arg2, arg3);
}

export function Bookmarks(arg1) {
  return window['go']['app']['Bookmarks']['Bookmarks'](arg1);
}

export function DeleteBookmark(arg1, arg2) {
  return window['go']['app']['Bookmarks']['DeleteBookmark'](arg1, arg2);
}
