// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBookmark(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Bookmarks(arg1:string):Promise<string>;

export function DeleteBookmark(arg1:string,arg2:string):Promise<void>;
