// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close(arg1) {
  return window['go']['main']['App']['Close'](arg1);
}

export function CountLines(arg1, arg2) {
  return window['go']['main']['App']['CountLines'](arg1, arg2);
}

export function Filters(arg1) {
  return window['go']['main']['App']['Filters'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Import(arg1) {
  return window['go']['main']['App']['Import'](arg1);
}

export function LoadSettings(arg1) {
  return window['go']['main']['App']['LoadSettings'](arg1);
}

export function LuaOutput(arg1) {
  return window['go']['main']['App']['LuaOutput'](arg1);
}

export function Open(arg1) {
  return window['go']['main']['App']['Open'](arg1);
}

export function OpenProjectDirectory(arg1) {
  return window['go']['main']['App']['OpenProjectDirectory'](arg1);
}

export function PreviewTemplate(arg1) {
  return window['go']['main']['App']['PreviewTemplate'](arg1);
}

export function Projects() {
  return window['go']['main']['App']['Projects']();
}

export function Query(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Query'](arg1, arg2, arg3, arg4);
}

export function Reload(arg1) {
  return window['go']['main']['App']['Reload'](arg1);
}

export function RunScript(arg1, arg2) {
  return window['go']['main']['App']['RunScript'](arg1, arg2);
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function SelectLogFileDialog() {
  return window['go']['main']['App']['SelectLogFileDialog']();
}

export function SelectProjectDirectoryDialog() {
  return window['go']['main']['App']['SelectProjectDirectoryDialog']();
}
