// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close(arg1:string):Promise<void>;

export function CountLines(arg1:string,arg2:string):Promise<number>;

export function Filters(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Import(arg1:string):Promise<string>;

export function LoadSettings(arg1:string):Promise<string>;

export function LuaOutput(arg1:string):Promise<string>;

export function Open(arg1:string):Promise<string>;

export function OpenProjectDirectory(arg1:string):Promise<void>;

export function PreviewTemplate(arg1:string):Promise<string>;

export function Projects():Promise<string>;

export function Query(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function Reload(arg1:string):Promise<void>;

export function RunScript(arg1:string,arg2:string):Promise<string>;

export function SaveSettings(arg1:string,arg2:string):Promise<void>;

export function SelectLogFileDialog():Promise<string>;

export function SelectProjectDirectoryDialog():Promise<string>;
